//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class Screen1 : Neo.ApplicationFramework.Controls.Controls.Form, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage {
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_MultiPicture;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_MultiPicture1;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_MultiPicture2;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_MultiPicture3;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_MultiPicture4;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_MultiPicture5;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_MultiPicture6;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_MultiPicture7;
        
        private bool m_Initialized_Screen1;
        
        public Screen1() {
            this.InitializeComponent();
            this.m_Button.Click += new System.EventHandler(this.m_Button_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter MultiPicture {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_MultiPicture);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter MultiPicture1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_MultiPicture1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter MultiPicture2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_MultiPicture2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter MultiPicture3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_MultiPicture3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter MultiPicture4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_MultiPicture4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter MultiPicture5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_MultiPicture5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter MultiPicture6 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_MultiPicture6);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter MultiPicture7 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_MultiPicture7);
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem1 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem2 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem3 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem4 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem5 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval6 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem6 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval7 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem7 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval8 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem8 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper6 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval9 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem9 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval10 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem10 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper7 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval11 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem11 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval12 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem12 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper8 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval13 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem13 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval14 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem14 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper9 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval15 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem15 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval16 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem16 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            this.m_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_AnalogNumeric = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_MultiPicture = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            this.m_MultiPicture1 = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            this.m_MultiPicture2 = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            this.m_MultiPicture3 = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            this.m_MultiPicture4 = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            this.m_MultiPicture5 = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            this.m_MultiPicture6 = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            this.m_MultiPicture7 = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture7)).BeginInit();
            this.SuspendLayout();
            // 
            // Screen1
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.SingleBorder;
            this.ControlBox = false;
            // 
            // m_Button
            // 
            this.m_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Button.BlinkDynamicsValue = false;
            this.m_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button.DelayMouseInputPeriod = 0;
            this.m_Button.EnabledDynamicsValue = true;
            this.m_Button.FontSizePixels = 15;
            this.m_Button.ForceTransparency = true;
            this.m_Button.Height = 84;
            this.m_Button.IndicatorMargin = null;
            this.m_Button.Left = 172;
            this.m_Button.Name = "m_Button";
            this.m_Button.RequiresTransparency = true;
            this.m_Button.ScreenOwnerName = "Screen1";
            this.m_Button.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Button.TextHeight = 18;
            this.m_Button.TextValue = 0D;
            this.m_Button.TextWidth = 113;
            this.m_Button.Top = 40;
            this.m_Button.Value = 0D;
            this.m_Button.VisibleDynamicsValue = true;
            this.m_Button.VisualPropertiesHashCode = 570927881;
            this.m_Button.Width = 123;
            // 
            // m_AnalogNumeric
            // 
            this.m_AnalogNumeric.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_AnalogNumeric.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_AnalogNumeric.BlinkDynamicsValue = false;
            this.m_AnalogNumeric.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_AnalogNumeric.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric.DisplayFormat = Neo.ApplicationFramework.Interfaces.AnalogNumericDisplayFormat.Decimal;
            this.m_AnalogNumeric.EnabledDynamicsValue = true;
            this.m_AnalogNumeric.FontSizePixels = 20;
            this.m_AnalogNumeric.Height = 75;
            this.m_AnalogNumeric.Left = 392;
            this.m_AnalogNumeric.Name = "m_AnalogNumeric";
            this.m_AnalogNumeric.NumberOfDecimals = 5;
            this.m_AnalogNumeric.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric.ScreenOwnerName = "Screen1";
            this.m_AnalogNumeric.Top = 45;
            this.m_AnalogNumeric.VisibleDynamicsValue = true;
            this.m_AnalogNumeric.Width = 255;
            // 
            // m_MultiPicture
            // 
            this.m_MultiPicture.BlinkDynamicsValue = false;
            this.m_MultiPicture.DelayMouseInputPeriod = 0;
            this.m_MultiPicture.EnabledDynamicsValue = true;
            this.m_MultiPicture.Height = 54;
            this.m_MultiPicture.Left = 99;
            this.m_MultiPicture.Name = "m_MultiPicture";
            this.m_MultiPicture.ScreenOwnerName = "Screen1";
            this.m_MultiPicture.Stretch = true;
            multisymbolitem1.SymbolName = "button gray";
            multisymbolitem1.Transparent = false;
            symbolinterval1.Value = multisymbolitem1;
            symbolinterval2.End = 1D;
            symbolinterval2.Start = 1D;
            multisymbolitem2.SymbolName = "button green";
            multisymbolitem2.Transparent = false;
            symbolinterval2.Value = multisymbolitem2;
            symbolintervalmapper2.Intervals.Add(symbolinterval1);
            symbolintervalmapper2.Intervals.Add(symbolinterval2);
            this.m_MultiPicture.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_MultiPicture.SymbolName = "button gray";
            this.m_MultiPicture.Top = 220;
            this.m_MultiPicture.Value = 0D;
            this.m_MultiPicture.VisibleDynamicsValue = true;
            this.m_MultiPicture.Width = 56;
            // 
            // m_MultiPicture1
            // 
            this.m_MultiPicture1.BlinkDynamicsValue = false;
            this.m_MultiPicture1.DelayMouseInputPeriod = 0;
            this.m_MultiPicture1.EnabledDynamicsValue = true;
            this.m_MultiPicture1.Height = 54;
            this.m_MultiPicture1.Left = 172;
            this.m_MultiPicture1.Name = "m_MultiPicture1";
            this.m_MultiPicture1.ScreenOwnerName = "Screen1";
            this.m_MultiPicture1.Stretch = true;
            multisymbolitem3.SymbolName = "button gray";
            multisymbolitem3.Transparent = false;
            symbolinterval3.Value = multisymbolitem3;
            symbolinterval4.End = 1D;
            symbolinterval4.Start = 1D;
            multisymbolitem4.SymbolName = "button green";
            multisymbolitem4.Transparent = false;
            symbolinterval4.Value = multisymbolitem4;
            symbolintervalmapper3.Intervals.Add(symbolinterval3);
            symbolintervalmapper3.Intervals.Add(symbolinterval4);
            this.m_MultiPicture1.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_MultiPicture1.SymbolName = "button gray";
            this.m_MultiPicture1.Top = 220;
            this.m_MultiPicture1.Value = 0D;
            this.m_MultiPicture1.VisibleDynamicsValue = true;
            this.m_MultiPicture1.Width = 56;
            // 
            // m_MultiPicture2
            // 
            this.m_MultiPicture2.BlinkDynamicsValue = false;
            this.m_MultiPicture2.DelayMouseInputPeriod = 0;
            this.m_MultiPicture2.EnabledDynamicsValue = true;
            this.m_MultiPicture2.Height = 54;
            this.m_MultiPicture2.Left = 249;
            this.m_MultiPicture2.Name = "m_MultiPicture2";
            this.m_MultiPicture2.ScreenOwnerName = "Screen1";
            this.m_MultiPicture2.Stretch = true;
            multisymbolitem5.SymbolName = "button gray";
            multisymbolitem5.Transparent = false;
            symbolinterval5.Value = multisymbolitem5;
            symbolinterval6.End = 1D;
            symbolinterval6.Start = 1D;
            multisymbolitem6.SymbolName = "button green";
            multisymbolitem6.Transparent = false;
            symbolinterval6.Value = multisymbolitem6;
            symbolintervalmapper4.Intervals.Add(symbolinterval5);
            symbolintervalmapper4.Intervals.Add(symbolinterval6);
            this.m_MultiPicture2.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_MultiPicture2.SymbolName = "button gray";
            this.m_MultiPicture2.Top = 220;
            this.m_MultiPicture2.Value = 0D;
            this.m_MultiPicture2.VisibleDynamicsValue = true;
            this.m_MultiPicture2.Width = 56;
            // 
            // m_MultiPicture3
            // 
            this.m_MultiPicture3.BlinkDynamicsValue = false;
            this.m_MultiPicture3.DelayMouseInputPeriod = 0;
            this.m_MultiPicture3.EnabledDynamicsValue = true;
            this.m_MultiPicture3.Height = 54;
            this.m_MultiPicture3.Left = 324;
            this.m_MultiPicture3.Name = "m_MultiPicture3";
            this.m_MultiPicture3.ScreenOwnerName = "Screen1";
            this.m_MultiPicture3.Stretch = true;
            multisymbolitem7.SymbolName = "button gray";
            multisymbolitem7.Transparent = false;
            symbolinterval7.Value = multisymbolitem7;
            symbolinterval8.End = 1D;
            symbolinterval8.Start = 1D;
            multisymbolitem8.SymbolName = "button green";
            multisymbolitem8.Transparent = false;
            symbolinterval8.Value = multisymbolitem8;
            symbolintervalmapper5.Intervals.Add(symbolinterval7);
            symbolintervalmapper5.Intervals.Add(symbolinterval8);
            this.m_MultiPicture3.SymbolIntervalMapper = symbolintervalmapper5;
            this.m_MultiPicture3.SymbolName = "button gray";
            this.m_MultiPicture3.Top = 220;
            this.m_MultiPicture3.Value = 0D;
            this.m_MultiPicture3.VisibleDynamicsValue = true;
            this.m_MultiPicture3.Width = 56;
            // 
            // m_MultiPicture4
            // 
            this.m_MultiPicture4.BlinkDynamicsValue = false;
            this.m_MultiPicture4.DelayMouseInputPeriod = 0;
            this.m_MultiPicture4.EnabledDynamicsValue = true;
            this.m_MultiPicture4.Height = 54;
            this.m_MultiPicture4.Left = 399;
            this.m_MultiPicture4.Name = "m_MultiPicture4";
            this.m_MultiPicture4.ScreenOwnerName = "Screen1";
            this.m_MultiPicture4.Stretch = true;
            multisymbolitem9.SymbolName = "button gray";
            multisymbolitem9.Transparent = false;
            symbolinterval9.Value = multisymbolitem9;
            symbolinterval10.End = 1D;
            symbolinterval10.Start = 1D;
            multisymbolitem10.SymbolName = "button green";
            multisymbolitem10.Transparent = false;
            symbolinterval10.Value = multisymbolitem10;
            symbolintervalmapper6.Intervals.Add(symbolinterval9);
            symbolintervalmapper6.Intervals.Add(symbolinterval10);
            this.m_MultiPicture4.SymbolIntervalMapper = symbolintervalmapper6;
            this.m_MultiPicture4.SymbolName = "button gray";
            this.m_MultiPicture4.Top = 220;
            this.m_MultiPicture4.Value = 0D;
            this.m_MultiPicture4.VisibleDynamicsValue = true;
            this.m_MultiPicture4.Width = 56;
            // 
            // m_MultiPicture5
            // 
            this.m_MultiPicture5.BlinkDynamicsValue = false;
            this.m_MultiPicture5.DelayMouseInputPeriod = 0;
            this.m_MultiPicture5.EnabledDynamicsValue = true;
            this.m_MultiPicture5.Height = 54;
            this.m_MultiPicture5.Left = 474;
            this.m_MultiPicture5.Name = "m_MultiPicture5";
            this.m_MultiPicture5.ScreenOwnerName = "Screen1";
            this.m_MultiPicture5.Stretch = true;
            multisymbolitem11.SymbolName = "button gray";
            multisymbolitem11.Transparent = false;
            symbolinterval11.Value = multisymbolitem11;
            symbolinterval12.End = 1D;
            symbolinterval12.Start = 1D;
            multisymbolitem12.SymbolName = "button green";
            multisymbolitem12.Transparent = false;
            symbolinterval12.Value = multisymbolitem12;
            symbolintervalmapper7.Intervals.Add(symbolinterval11);
            symbolintervalmapper7.Intervals.Add(symbolinterval12);
            this.m_MultiPicture5.SymbolIntervalMapper = symbolintervalmapper7;
            this.m_MultiPicture5.SymbolName = "button gray";
            this.m_MultiPicture5.Top = 220;
            this.m_MultiPicture5.Value = 0D;
            this.m_MultiPicture5.VisibleDynamicsValue = true;
            this.m_MultiPicture5.Width = 56;
            // 
            // m_MultiPicture6
            // 
            this.m_MultiPicture6.BlinkDynamicsValue = false;
            this.m_MultiPicture6.DelayMouseInputPeriod = 0;
            this.m_MultiPicture6.EnabledDynamicsValue = true;
            this.m_MultiPicture6.Height = 54;
            this.m_MultiPicture6.Left = 549;
            this.m_MultiPicture6.Name = "m_MultiPicture6";
            this.m_MultiPicture6.ScreenOwnerName = "Screen1";
            this.m_MultiPicture6.Stretch = true;
            multisymbolitem13.SymbolName = "button gray";
            multisymbolitem13.Transparent = false;
            symbolinterval13.Value = multisymbolitem13;
            symbolinterval14.End = 1D;
            symbolinterval14.Start = 1D;
            multisymbolitem14.SymbolName = "button green";
            multisymbolitem14.Transparent = false;
            symbolinterval14.Value = multisymbolitem14;
            symbolintervalmapper8.Intervals.Add(symbolinterval13);
            symbolintervalmapper8.Intervals.Add(symbolinterval14);
            this.m_MultiPicture6.SymbolIntervalMapper = symbolintervalmapper8;
            this.m_MultiPicture6.SymbolName = "button gray";
            this.m_MultiPicture6.Top = 220;
            this.m_MultiPicture6.Value = 0D;
            this.m_MultiPicture6.VisibleDynamicsValue = true;
            this.m_MultiPicture6.Width = 56;
            // 
            // m_MultiPicture7
            // 
            this.m_MultiPicture7.BlinkDynamicsValue = false;
            this.m_MultiPicture7.DelayMouseInputPeriod = 0;
            this.m_MultiPicture7.EnabledDynamicsValue = true;
            this.m_MultiPicture7.Height = 54;
            this.m_MultiPicture7.Left = 626;
            this.m_MultiPicture7.Name = "m_MultiPicture7";
            this.m_MultiPicture7.ScreenOwnerName = "Screen1";
            this.m_MultiPicture7.Stretch = true;
            multisymbolitem15.SymbolName = "button gray";
            multisymbolitem15.Transparent = false;
            symbolinterval15.Value = multisymbolitem15;
            symbolinterval16.End = 1D;
            symbolinterval16.Start = 1D;
            multisymbolitem16.SymbolName = "button green";
            multisymbolitem16.Transparent = false;
            symbolinterval16.Value = multisymbolitem16;
            symbolintervalmapper9.Intervals.Add(symbolinterval15);
            symbolintervalmapper9.Intervals.Add(symbolinterval16);
            this.m_MultiPicture7.SymbolIntervalMapper = symbolintervalmapper9;
            this.m_MultiPicture7.SymbolName = "button gray";
            this.m_MultiPicture7.Top = 220;
            this.m_MultiPicture7.Value = 0D;
            this.m_MultiPicture7.VisibleDynamicsValue = true;
            this.m_MultiPicture7.Width = 56;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "Screen1";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_Screen1 = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_Screen1) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Button);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric);
            this.DrawingPrimitives.Add(this.m_MultiPicture);
            this.DrawingPrimitives.Add(this.m_MultiPicture1);
            this.DrawingPrimitives.Add(this.m_MultiPicture2);
            this.DrawingPrimitives.Add(this.m_MultiPicture3);
            this.DrawingPrimitives.Add(this.m_MultiPicture4);
            this.DrawingPrimitives.Add(this.m_MultiPicture5);
            this.DrawingPrimitives.Add(this.m_MultiPicture6);
            this.DrawingPrimitives.Add(this.m_MultiPicture7);
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture7)).EndInit();
        }
        
        private void m_Button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "Click", "Toggle Tag", "Tags.MAIN_Variable_Bool", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.MAIN_Variable_Bool.ToggleTag();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Screen1));
            this.m_Button.Text = resources.GetText("Screen1.Button.Text", "Variable Bool");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage() {
            this.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageFont(this.GetCurrentLanguage(), this.FontTemplatesEnabled());
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_Screen1) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.MAIN_Variable_Real"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.MAIN_Salida_00"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_MultiPicture.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.MAIN_Salida_01"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_MultiPicture1.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding4 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.MAIN_Salida_02"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_MultiPicture2.DataBindings.Add(dynamicBinding4);
            this.m_DynamicBindings.Add(dynamicBinding4);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding5 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.MAIN_Salida_03"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_MultiPicture3.DataBindings.Add(dynamicBinding5);
            this.m_DynamicBindings.Add(dynamicBinding5);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding6 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.MAIN_Salida_04"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_MultiPicture4.DataBindings.Add(dynamicBinding6);
            this.m_DynamicBindings.Add(dynamicBinding6);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding7 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.MAIN_Salida_05"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_MultiPicture5.DataBindings.Add(dynamicBinding7);
            this.m_DynamicBindings.Add(dynamicBinding7);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding8 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.MAIN_Salida_06"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_MultiPicture6.DataBindings.Add(dynamicBinding8);
            this.m_DynamicBindings.Add(dynamicBinding8);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding9 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.MAIN_Salida_07"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_MultiPicture7.DataBindings.Add(dynamicBinding9);
            this.m_DynamicBindings.Add(dynamicBinding9);
        }
    }
}
