//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	public partial class Tags : Neo.ApplicationFramework.Tools.OpcClient.GlobalController, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage
	{
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag MAIN_Salida_00;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag MAIN_Salida_01;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag MAIN_Salida_02;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag MAIN_Salida_03;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag MAIN_Salida_04;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag MAIN_Salida_05;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag MAIN_Salida_06;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag MAIN_Salida_07;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag MAIN_Variable_Bool;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag MAIN_Variable_Real;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup2;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup3;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup4;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup5;
		
		public Tags()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			this.InitializeBeginInits();
			this.InitializeObjects();
			this.InitializeEndInits();
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public virtual void ConnectDataBindings()
		{
		}
		
		private void InitializeObjectCreations()
		{
			this.MAIN_Salida_00 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("MAIN_Salida_00", "Beckhoff.DataItem1", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.MAIN_Salida_01 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("MAIN_Salida_01", "Beckhoff.DataItem2", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.MAIN_Salida_02 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("MAIN_Salida_02", "Beckhoff.DataItem3", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.MAIN_Salida_03 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("MAIN_Salida_03", "Beckhoff.DataItem4", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.MAIN_Salida_04 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("MAIN_Salida_04", "Beckhoff.DataItem5", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.MAIN_Salida_05 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("MAIN_Salida_05", "Beckhoff.DataItem6", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.MAIN_Salida_06 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("MAIN_Salida_06", "Beckhoff.DataItem7", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.MAIN_Salida_07 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("MAIN_Salida_07", "Beckhoff.DataItem8", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.MAIN_Variable_Bool = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("MAIN_Variable_Bool", "Beckhoff.DataItem9", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.MAIN_Variable_Real = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("MAIN_Variable_Real", "Beckhoff.DataItem10", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.PollGroup1 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup2 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup3 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup4 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup5 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
		}
		
		private void InitializeBeginInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
		}
		
		private void InitializeEndInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).EndInit();
		}
		
		private void InitializeObjects()
		{
			this.LightweightTags.Add(this.MAIN_Salida_00);
			this.LightweightTags.Add(this.MAIN_Salida_01);
			this.LightweightTags.Add(this.MAIN_Salida_02);
			this.LightweightTags.Add(this.MAIN_Salida_03);
			this.LightweightTags.Add(this.MAIN_Salida_04);
			this.LightweightTags.Add(this.MAIN_Salida_05);
			this.LightweightTags.Add(this.MAIN_Salida_06);
			this.LightweightTags.Add(this.MAIN_Salida_07);
			this.LightweightTags.Add(this.MAIN_Variable_Bool);
			this.LightweightTags.Add(this.MAIN_Variable_Real);
			this.PollGroup1.Interval = 500;
			this.PollGroup1.Name = "PollGroup1";
			this.PollGroup2.Interval = 500;
			this.PollGroup2.Name = "PollGroup2";
			this.PollGroup3.Interval = 500;
			this.PollGroup3.Name = "PollGroup3";
			this.PollGroup4.Interval = 500;
			this.PollGroup4.Name = "PollGroup4";
			this.PollGroup5.Interval = 500;
			this.PollGroup5.Name = "PollGroup5";
			this.PollGroups.Add(this.PollGroup1);
			this.PollGroups.Add(this.PollGroup2);
			this.PollGroups.Add(this.PollGroup3);
			this.PollGroups.Add(this.PollGroup4);
			this.PollGroups.Add(this.PollGroup5);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Tags));
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage()
		{
			this.ApplyLanguage();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected virtual void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
		}
	}
}
